services:

  # Nginx
  nginx:
    image: nginx:1.27.2
    ports:
      - 80:80
    volumes:
      # ./フォルダをコンテナ内の/var/www/htmlにマウント
      - ./:/var/www/html
      # ./docker/nginxフォルダをコンテナ内の/etc/nginx/conf.dにマウント
      - ./docker/nginx:/etc/nginx/conf.d
    # 依存関係を設定
    depends_on:
      - app
      
  # PHP-FPM
  app:
    build:
      # Dockerfileを格納するフォルダのパス
      context: ./docker/php
      # Dockerfileのファイル名
      dockerfile: Dockerfile
    # コンテナ内で使用される環境変数を定義
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      # ./フォルダをコンテナ内の/var/www/htmlにマウント
      - ./:/var/www/html
    depends_on:
      - mysql

  #　WorkerServer
  worker:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    command: php /var/www/html/artisan queue:listen
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - ./:/var/www/html
    depends_on:
    - mysql
    - redis
    privileged: true
  
  #　Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  # MySQL
  mysql:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      # 名前付きボリュームを MySQL コンテナに紐づける
      - mysqldata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      PMA_HOSTS: ${DB_HOST}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
      
volumes:
  # 名前付きボリュームの作成
  mysqldata: